Product.create(name: 'Prince Polo', price: 199, menu_category: 'food', image_url: 'https://i.imgur.com/l4tEqmL.png')
# Product.create(name: 'Donut Chocolate', price: 129, menu_category: 'food', image_url: 'https://i.imgur.com/LRwEakM.png')
# Product.create(name: 'Donut limited', price: 159, menu_category: 'food', image_url: 'https://i.imgur.com/3sgNWeJ.png')
# Product.create(name: 'Banana', price: 99, menu_category: 'food', image_url: 'https://i.imgur.com/eUzrUjG.png')
# Product.create(name: 'Mullermilch CoCo', price: 499, menu_category: 'drinks', image_url: 'https://i.imgur.com/OGLkpV5.png')
# Product.create(name: 'Mullermilch Chocolate', price: 499, menu_category: 'drinks', image_url: 'https://i.imgur.com/fCHrRRT.png')
# Product.create(name: 'Mullermilch Strawberry', price: 499, menu_category: 'drinks', image_url: 'https://i.imgur.com/0HICucM.png')
Product.create(name: 'Monster classic', price: 599, menu_category: 'drinks', image_url: 'https://i.imgur.com/WEDXcDi.png')
Product.create(name: 'Monster juiced', price: 599, menu_category: 'drinks', image_url: 'https://i.imgur.com/QNLaQ9L.png')
Product.create(name: 'Polaris Gazowana', price: 199, menu_category: 'drinks', image_url: 'https://i.imgur.com/7BGt24V.png')
Product.create(name: 'Polaris Niegazowana', price: 159, menu_category: 'drinks', image_url: 'https://i.imgur.com/CkaVyAQ.png')
Product.create(name: 'Sezamki Classic', price: 399, menu_category: 'food', image_url: 'https://i.imgur.com/r1pZQ1P.png')
Product.create(name: 'Rafaello', price: 99, menu_category: 'food', image_url: 'https://i.imgur.com/XwLtkud.png')
Product.create(name: 'Mini Bounty', price: 59, menu_category: 'food', image_url: 'https://i.imgur.com/JasXScr.png')
Product.create(name: 'Mini Snickers', price: 59, menu_category: 'food', image_url: 'https://i.imgur.com/ORYBJqE.png')
